namespace medic_system.Models
{
    public class CrearConsultaMedicaRequest
    {
        public DateTime FechaCreacionConsulta { get; set; }
        public string UsuarioCreacionConsulta { get; set; }
        public string HistorialConsulta { get; set; }
        public string SecuencialConsulta { get; set; }
        public int PacienteConsultaP { get; set; }
        public string MotivoConsulta { get; set; }
        public string EnfermedadConsulta { get; set; }
        public string NombreParienteConsulta { get; set; }
        public int TipoParienteConsulta { get; set; }
        public int TelefonoConsulta { get; set; }
        public string TemperaturaConsulta { get; set; }
        public string FrecuenciaRespiratoriaConsulta { get; set; }
        public string PresionArterialSistolicaConsulta { get; set; }
        public string PresionArterialDiastolicaConsulta { get; set; }
        public string PulsoConsulta { get; set; }
        public string PesoConsulta { get; set; }
        public string TallaConsulta { get; set; }
        public string PlanTratamientoConsulta { get; set; }
        public string ObservacionConsulta { get; set; }
        public string AntecedentesPersonalesConsulta { get; set; }
        public int DiasIncapacidadConsulta { get; set; }
        public int MedicoConsultaD { get; set; }
        public int EspecialidadId { get; set; }
        public int EstadoConsultaC { get; set; }
        public int TipoConsultaC { get; set; }
        public string NotasEvolucionConsulta { get; set; }
        public string ConsultaPrincipalConsulta { get; set; }
        public int ActivoConsulta { get; set; }
        public int MedicamentoId { get; set; }
        public int DosisMedicamento { get; set; }
        public string ObservacionMedicamento { get; set; }
        public int ImagenId { get; set; }
        public string ObservacionImagen { get; set; }
        public int CantidadImagen { get; set; }
        public int DiagnosticoId { get; set; }
        public string ObservacionDiagnostico { get; set; }
        public bool PresuntivoDiagnosticos { get; set; }
        public bool DefinitivoDiagnosticos { get; set; }
        public bool Cardiopatia { get; set; }
        public string ObserCardiopatia { get; set; }
        public bool Diabetes { get; set; }
        public string ObserDiabetes { get; set; }
        public bool EnfCardiovascular { get; set; }
        public string ObserEnfCardiovascular { get; set; }
        public bool Hipertension { get; set; }
        public string ObserHipertension { get; set; }
        public bool Cancer { get; set; }
        public string ObserCancer { get; set; }
        public bool Tuberculosis { get; set; }
        public string ObserTuberculosis { get; set; }
        public bool EnfMental { get; set; }
        public string ObserEnfMental { get; set; }
        public bool EnfInfecciosa { get; set; }
        public string ObserEnfInfecciosa { get; set; }
        public bool MalFormacion { get; set; }
        public string ObserMalFormacion { get; set; }
        public string Otro { get; set; }
        public string ObserOtro { get; set; }
        public string Alergias { get; set; }
        public string ObserAlergias { get; set; }
        public string Cirugias { get; set; }
        public string ObserCirugias { get; set; }
        public bool Cabeza { get; set; }
        public string ObserCabeza { get; set; }
        public bool Cuello { get; set; }
        public string ObserCuello { get; set; }
        public bool Torax { get; set; }
        public string ObserTorax { get; set; }
        public bool Abdomen { get; set; }
        public string ObserAbdomen { get; set; }
        public bool Pelvis { get; set; }
        public string ObserPelvis { get; set; }
        public bool Extremidades { get; set; }
        public string ObserExtremidades { get; set; }
        public bool OrgSentidos { get; set; }
        public string ObserOrgSentidos { get; set; }
        public bool Respiratorio { get; set; }
        public string ObserRespiratorio { get; set; }
        public bool CardioVascular { get; set; }
        public string ObserCardioVascular { get; set; }
        public bool Digestivo { get; set; }
        public string ObserDigestivo { get; set; }
        public bool Genital { get; set; }
        public string ObserGenital { get; set; }
        public bool Urinario { get; set; }
        public string ObserUrinario { get; set; }
        public bool MEsqueletico { get; set; }
        public string ObserMEsqueletico { get; set; }
        public bool Endocrino { get; set; }
        public string ObserEndocrino { get; set; }
        public bool Linfatico { get; set; }
        public string ObserLinfatico { get; set; }
        public bool Nervioso { get; set; }
        public string ObserNervioso { get; set; }
        public int CatalogoLaboratorioId { get; set; }
        public int CantidadLaboratorio { get; set; }
        public string Observacion { get; set; }
    }

}
